// Resource route — no component export.
// Streams the live presence roster for a lesson via Server-Sent Events.
// Also handles POST (heartbeat) and DELETE (explicit leave) from the client hook.

import { randomUUID } from "node:crypto";
import { getCurrentUserId } from "~/lib/session";
import { getUserById } from "~/services/userService";
import {
  join,
  leave,
  subscribe,
  getRoster,
  heartbeat,
} from "~/lib/presenceStore";
// Route types generated by react-router typegen; define inline since typegen needs vite
type RouteArgs = { params: Record<string, string>; request: Request };

// ── GET — SSE stream ─────────────────────────────────────────────────────────

export async function loader({ params, request }: RouteArgs) {
  const lessonId = Number(params.lessonId);
  if (isNaN(lessonId)) {
    return new Response("Invalid lesson ID", { status: 400 });
  }

  const userId = await getCurrentUserId(request);
  if (!userId) {
    return new Response("Unauthorized", { status: 401 });
  }

  const user = getUserById(userId);
  if (!user) {
    return new Response("User not found", { status: 404 });
  }

  const presenceUser = {
    id: user.id,
    name: user.name,
    avatarUrl: user.avatarUrl ?? null,
  };

  const connectionId = randomUUID();

  // Register this connection in the store
  join(lessonId, userId, presenceUser, connectionId);

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    start(controller) {
      function send(roster: ReturnType<typeof getRoster>) {
        const event = `data: ${JSON.stringify(roster)}\n\n`;
        try {
          controller.enqueue(encoder.encode(event));
        } catch {
          // Stream already closed — ignore
        }
      }

      // Browser reconnect directive
      controller.enqueue(encoder.encode("retry: 2000\n\n"));

      // Send the connectionId to the client so it can send heartbeats and
      // explicit leave requests tied to this specific SSE connection.
      controller.enqueue(
        encoder.encode(
          `event: connection\ndata: ${JSON.stringify({ id: connectionId })}\n\n`
        )
      );

      // Subscribe first, then send current roster so we don't miss changes
      // that arrive between subscribe() and the initial push
      const unsubscribe = subscribe(lessonId, send);

      // Push the current roster immediately (join() already ran above)
      send(getRoster(lessonId));

      // Clean up when the client disconnects (AbortSignal fires on TCP close)
      request.signal.addEventListener("abort", () => {
        unsubscribe();
        leave(lessonId, userId, connectionId);
        try {
          controller.close();
        } catch {
          // Already closed
        }
      });
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}

// ── POST / DELETE — heartbeat & explicit leave ───────────────────────────────

export async function action({ params, request }: RouteArgs) {
  const lessonId = Number(params.lessonId);
  if (isNaN(lessonId)) {
    return new Response("Invalid lesson ID", { status: 400 });
  }

  const userId = await getCurrentUserId(request);
  if (!userId) {
    return new Response("Unauthorized", { status: 401 });
  }

  let body: { connectionId?: string } = {};
  try {
    body = await request.json();
  } catch {
    return new Response("Invalid JSON", { status: 400 });
  }

  const { connectionId } = body;
  if (!connectionId) {
    return new Response("Missing connectionId", { status: 400 });
  }

  if (request.method === "POST") {
    // Heartbeat — refresh the last-seen timestamp so the eviction timer
    // doesn't prematurely remove this user from the roster.
    heartbeat(connectionId);
    return new Response(null, { status: 204 });
  }

  if (request.method === "DELETE") {
    // Explicit leave — remove this connection immediately without waiting for
    // the SSE TCP connection to close (which may be delayed or never happen
    // when the client's network was interrupted uncleanly).
    leave(lessonId, userId, connectionId);
    return new Response(null, { status: 204 });
  }

  return new Response("Method not allowed", { status: 405 });
}
