// Resource route — no component export.
// Streams the live presence roster for a lesson via Server-Sent Events.

import { getCurrentUserId } from "~/lib/session";
import { getUserById } from "~/services/userService";
import { join, leave, subscribe, getRoster } from "~/lib/presenceStore";
// Route types generated by react-router typegen; define inline since typegen needs vite
type LoaderArgs = { params: Record<string, string>; request: Request };

export async function loader({ params, request }: LoaderArgs) {
  const lessonId = Number(params.lessonId);
  if (isNaN(lessonId)) {
    return new Response("Invalid lesson ID", { status: 400 });
  }

  const userId = await getCurrentUserId(request);
  if (!userId) {
    return new Response("Unauthorized", { status: 401 });
  }

  const user = getUserById(userId);
  if (!user) {
    return new Response("User not found", { status: 404 });
  }

  const presenceUser = {
    id: user.id,
    name: user.name,
    avatarUrl: user.avatarUrl ?? null,
  };

  // Register this connection in the store
  join(lessonId, userId, presenceUser);

  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    start(controller) {
      function send(roster: ReturnType<typeof getRoster>) {
        const event = `data: ${JSON.stringify(roster)}\n\n`;
        try {
          controller.enqueue(encoder.encode(event));
        } catch {
          // Stream already closed — ignore
        }
      }

      // Browser reconnect directive
      controller.enqueue(encoder.encode("retry: 2000\n\n"));

      // Subscribe first, then send current roster so we don't miss changes
      // that arrive between subscribe() and the initial push
      const unsubscribe = subscribe(lessonId, send);

      // Push the current roster immediately (join() already ran above)
      send(getRoster(lessonId));

      // Clean up when the client disconnects (AbortSignal fires on TCP close)
      request.signal.addEventListener("abort", () => {
        unsubscribe();
        leave(lessonId, userId);
        try {
          controller.close();
        } catch {
          // Already closed
        }
      });
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    },
  });
}
